from re import S
import pandas as pd
import streamlit as st
import numpy as np

def app():
    st.write("# K-Nearest Neighbor Classification")
    st.write("The reason we choose KNN is the KNN algorithm can compete with the most accurate models because it deliver highly precise predictions. As a result, the KNN algorithm can be used in applications that require high accuracy but don't require a human-readable model.")
    st.write("We used the following parameters in the models - ")
    data = {
        "neighbors" : [3, 5, 7],
    }
    df = pd.DataFrame(data=data)
    st.table(df)
    st.write("## Experiment 1: The figures below shown us the ROC Curves of KNN with the hyperparameters (neighbors=3)")

    st.write("The table below is the classification report generated by using KNN Classifier Num_of_Baskets.")
    df1 = pd.read_csv('BASKETS_KNN_Report.csv', index_col=0)
    st.dataframe(df1)
    st.write("The table below is the classification report generated by using KNN Classifier for Age_Range.")
    df1 = pd.read_csv('AGE_KNN_Report.csv', index_col=0)
    st.dataframe(df1)
    st.write("The table below is the classification report generated by using KNN Classifier Num_of_Baskets with smote.")
    df1 = pd.read_csv('SMOTE_BASKETS_KNN_Report.csv', index_col=0)
    st.dataframe(df1)
    st.write("The table below is the classification report generated by using KNN Classifier for Age_Range with smote.")
    df1 = pd.read_csv('SMOTE_AGE_KNN_Report.csv', index_col=0)
    st.dataframe(df1)
    
    st.write("The Accuracy and Confusion Matrix for baskets are shown as below:")
    a_file = open("BASKETS_KNN_ACC.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.write("The Accuracy and Confusion Matrix for Age are shown as below:")
    a_file = open("AGE_KNN_ACC.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    
    st.write("The Accuracy and Confusion Matrix for baskets with smote are shown as below:")
    a_file = open("SMOTE_BASKETS_KNN_ACC.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.write("The Accuracy and Confusion Matrix for Age with smote are shown as below:")
    a_file = open("SMOTE_AGE_KNN_ACC.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.image(['BASKETS_KNN_ROC.png', 'SMOTE_BASKETS_KNN_ROC.png'])
    st.image(['AGE_KNN_ROC.png', 'SMOTE_AGE_KNN_ROC.png'])

    st.write("The AUC for all baskets are shown as below:")
    a_file = open("BASKETS_KNN_AUC.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    st.write("The AUC for all AGE are shown as below:")
    a_file = open("AGE_KNN_AUC.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    
    st.write("The AUC for all baskets with smote are shown as below:")
    a_file = open("SMOTE_BASKETS_KNN_AUC.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    st.write("The AUC for all AGE are with smote shown as below:")
    a_file = open("SMOTE_AGE_KNN_AUC.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.write("## Experiment 2: The figures below shown us the ROC Curves of KNN with the hyperparameters (neighbors=5)")

    st.write("The table below is the classification report generated by using KNN Classifier Num_of_Baskets.")
    df1 = pd.read_csv('BASKETS_KNN_Report1.csv', index_col=0)
    st.dataframe(df1)
    st.write("The table below is the classification report generated by using KNN Classifier for Age_Range.")
    df1 = pd.read_csv('AGE_KNN_Report1.csv', index_col=0)
    st.dataframe(df1)
    st.write("The table below is the classification report generated by using KNN Classifier Num_of_Baskets with smote.")
    df1 = pd.read_csv('SMOTE_BASKETS_KNN_Report1.csv', index_col=0)
    st.dataframe(df1)
    st.write("The table below is the classification report generated by using KNN Classifier for Age_Range with smote.")
    df1 = pd.read_csv('SMOTE_AGE_KNN_Report1.csv', index_col=0)
    st.dataframe(df1)

    st.write("The Accuracy and Confusion Matrix for baskets are shown as below:")
    a_file = open("BASKETS_KNN_ACC1.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.write("The Accuracy and Confusion Matrix for Age are shown as below:")
    a_file = open("AGE_KNN_ACC1.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    
    st.write("The Accuracy and Confusion Matrix for baskets with smote are shown as below:")
    a_file = open("SMOTE_BASKETS_KNN_ACC1.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.write("The Accuracy and Confusion Matrix for Age with smote are shown as below:")
    a_file = open("SMOTE_AGE_KNN_ACC1.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.image(['BASKETS_KNN_ROC1.png', 'SMOTE_BASKETS_KNN_ROC1.png'])
    st.image(['AGE_KNN_ROC1.png', 'SMOTE_AGE_KNN_ROC1.png'])

    st.write("The AUC for all baskets are shown as below:")
    a_file = open("BASKETS_KNN_AUC1.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    st.write("The AUC for all AGE are shown as below:")
    a_file = open("AGE_KNN_AUC1.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    
    st.write("The AUC for all baskets with smote are shown as below:")
    a_file = open("SMOTE_BASKETS_KNN_AUC1.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    st.write("The AUC for all AGE are with smote shown as below:")
    a_file = open("SMOTE_AGE_KNN_AUC1.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.write("## Experiment 3: The figures below shown us the ROC Curves of KNN with the hyperparameters (neighbors=7)")

    st.write("The table below is the classification report generated by using KNN Classifier Num_of_Baskets.")
    df1 = pd.read_csv('BASKETS_KNN_Report2.csv', index_col=0)
    st.dataframe(df1)
    st.write("The table below is the classification report generated by using KNN Classifier for Age_Range.")
    df1 = pd.read_csv('AGE_KNN_Report2.csv', index_col=0)
    st.dataframe(df1)
    st.write("The table below is the classification report generated by using KNN Classifier Num_of_Baskets with smote.")
    df1 = pd.read_csv('SMOTE_BASKETS_KNN_Report2.csv', index_col=0)
    st.dataframe(df1)
    st.write("The table below is the classification report generated by using KNN Classifier for Age_Range with smote.")
    df1 = pd.read_csv('SMOTE_AGE_KNN_Report2.csv', index_col=0)
    st.dataframe(df1)

    st.write("The Accuracy and Confusion Matrix for baskets are shown as below:")
    a_file = open("BASKETS_KNN_ACC2.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.write("The Accuracy and Confusion Matrix for Age are shown as below:")
    a_file = open("AGE_KNN_ACC2.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.write("The Accuracy and Confusion Matrix for baskets with smote are shown as below:")
    a_file = open("SMOTE_BASKETS_KNN_ACC2.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.write("The Accuracy and Confusion Matrix for Age with smote are shown as below:")
    a_file = open("SMOTE_AGE_KNN_ACC2.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    
    st.image(['BASKETS_KNN_ROC2.png', 'SMOTE_BASKETS_KNN_ROC2.png'])
    st.image(['AGE_KNN_ROC2.png', 'SMOTE_AGE_KNN_ROC2.png'])

    st.write("The AUC for all baskets are shown as below:")
    a_file = open("BASKETS_KNN_AUC2.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    st.write("The AUC for all AGE are shown as below:")
    a_file = open("AGE_KNN_AUC2.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    
    st.write("The AUC for all baskets with smote are shown as below:")
    a_file = open("SMOTE_BASKETS_KNN_AUC2.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    st.write("The AUC for all AGE are with smote shown as below:")
    a_file = open("SMOTE_AGE_KNN_AUC2.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")