from re import S
import pandas as pd
import streamlit as st
import numpy as np

def app():
    st.write("# Random Forest Classification")
    st.write("For the dataset we using, it consists of multiclass problems and Random Forest algorithm is well suited to multiclass situations so this is why we choose Random Forest. Random Forest can also be used to combine numerical and categorical data. Each classifier in the ensemble is a decision tree classifier, with each node's split determined by a random selection of attributes. Each tree votes during classification, and the most popular class is returned.")
    st.write("We used the following parameters in the models - ")
    data = {
        "depth" : [5, 10, 5],
        "trees" : [1000, 1000, 500]
    }
    df = pd.DataFrame(data=data)
    st.table(df)

    st.write("## Experiment 1: The figures below shown us the ROC Curves of Random Forest Classifier with the hyperparameters (random\_state=1, n\_estimators=1000, max\_depth=5)")

    st.write("The table below is the classification report generated by using Random Forest Classifier Num_of_Baskets.")
    df1 = pd.read_csv('BASKETS_RF_Report.csv', index_col=0)
    st.dataframe(df1)
    st.write("The table below is the classification report generated by using Random Forest Classifier for Age_Range.")
    df1 = pd.read_csv('AGE_RF_Report.csv', index_col=0)
    st.dataframe(df1)
    st.write("The table below is the classification report generated by using Random Forest Classifier Num_of_Baskets with smote.")
    df1 = pd.read_csv('SMOTE_BASKETS_RF_Report.csv', index_col=0)
    st.dataframe(df1)
    st.write("The table below is the classification report generated by using Random Forest Classifier for Age_Range with smote.")
    df1 = pd.read_csv('SMOTE_AGE_RF_Report.csv', index_col=0)
    st.dataframe(df1)
    
    st.write("The Accuracy and Confusion Matrix for baskets are shown as below:")
    a_file = open("BASKETS_RF_ACC.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.write("The Accuracy and Confusion Matrix for Age are shown as below:")
    a_file = open("AGE_RF_ACC.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.write("The Accuracy and Confusion Matrix for baskets with smote are shown as below:")
    a_file = open("SMOTE_BASKETS_RF_ACC.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.write("The Accuracy and Confusion Matrix for Age with smote are shown as below:")
    a_file = open("SMOTE_AGE_RF_ACC.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    
    st.image(['BASKETS_RF_ROC.png', 'SMOTE_BASKETS_RF_ROC.png'])
    st.image(['AGE_RF_ROC.png', 'SMOTE_AGE_RF_ROC.png'])

    st.write("The AUC for all baskets are shown as below:")
    a_file = open("BASKETS_RF_AUC.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    st.write("The AUC for all AGE are shown as below:")
    a_file = open("AGE_RF_AUC.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    
    st.write("The AUC for all baskets with smote are shown as below:")
    a_file = open("SMOTE_BASKETS_RF_AUC.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    st.write("The AUC for all AGE with smote are shown as below:")
    a_file = open("SMOTE_AGE_RF_AUC.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.write("## Experiment 2: The figures below shown us the ROC Curves of Random Forest Classifier with the hyperparameters (random\_state=1, n\_estimators=1000, max\_depth=10)")

    st.write("The table below is the classification report generated by using Random Forest Classifier Num_of_Baskets.")
    df1 = pd.read_csv('BASKETS_RF_Report1.csv', index_col=0)
    st.dataframe(df1)
    st.write("The table below is the classification report generated by using Random Forest Classifier for Age_Range.")
    df1 = pd.read_csv('AGE_RF_Report1.csv', index_col=0)
    st.dataframe(df1)
    st.write("The table below is the classification report generated by using Random Forest Classifier Num_of_Baskets with smote.")
    df1 = pd.read_csv('SMOTE_BASKETS_RF_Report1.csv', index_col=0)
    st.dataframe(df1)
    st.write("The table below is the classification report generated by using Random Forest Classifier for Age_Range with smote.")
    df1 = pd.read_csv('SMOTE_AGE_RF_Report1.csv', index_col=0)
    st.dataframe(df1)

    st.write("The Accuracy and Confusion Matrix for baskets are shown as below:")
    a_file = open("BASKETS_RF_ACC1.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.write("The Accuracy and Confusion Matrix for Age are shown as below:")
    a_file = open("AGE_RF_ACC1.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    
    st.write("The Accuracy and Confusion Matrix for baskets with smote are shown as below:")
    a_file = open("SMOTE_BASKETS_RF_ACC1.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.write("The Accuracy and Confusion Matrix for Age with smote are shown as below:")
    a_file = open("SMOTE_AGE_RF_ACC1.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.image(['BASKETS_RF_ROC1.png', 'SMOTE_BASKETS_RF_ROC1.png'])
    st.image(['AGE_RF_ROC1.png', 'SMOTE_AGE_RF_ROC1.png'])

    st.write("The AUC for all baskets are shown as below:")
    a_file = open("BASKETS_RF_AUC1.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    st.write("The AUC for all AGE are shown as below:")
    a_file = open("AGE_RF_AUC1.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    
    st.write("The AUC for all baskets with smote are shown as below:")
    a_file = open("SMOTE_BASKETS_RF_AUC1.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    st.write("The AUC for all AGE with smote are shown as below:")
    a_file = open("SMOTE_AGE_RF_AUC1.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.write("## Experiment 3: The figures below shown us the ROC Curves of Random Forest Classifier with the hyperparameters (random\_state=1, n\_estimators=500, max\_depth=5)")

    st.write("The table below is the classification report generated by using Random Forest Classifier Num_of_Baskets.")
    df1 = pd.read_csv('BASKETS_RF_Report2.csv', index_col=0)
    st.dataframe(df1)
    st.write("The table below is the classification report generated by using Random Forest Classifier for Age_Range.")
    df1 = pd.read_csv('AGE_RF_Report2.csv', index_col=0)
    st.dataframe(df1)
    st.write("The table below is the classification report generated by using Random Forest Classifier Num_of_Baskets with smote.")
    df1 = pd.read_csv('SMOTE_BASKETS_RF_Report2.csv', index_col=0)
    st.dataframe(df1)
    st.write("The table below is the classification report generated by using Random Forest Classifier for Age_Range with smote.")
    df1 = pd.read_csv('SMOTE_AGE_RF_Report2.csv', index_col=0)
    st.dataframe(df1)

    st.write("The Accuracy and Confusion Matrix for baskets are shown as below:")
    a_file = open("BASKETS_RF_ACC2.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.write("The Accuracy and Confusion Matrix for Age are shown as below:")
    a_file = open("AGE_RF_ACC2.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    
    st.write("The Accuracy and Confusion Matrix for baskets with smote are shown as below:")
    a_file = open("SMOTE_BASKETS_RF_ACC2.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.write("The Accuracy and Confusion Matrix for Age with smote are shown as below:")
    a_file = open("SMOTE_AGE_RF_ACC2.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")

    st.image(['BASKETS_RF_ROC2.png', 'SMOTE_BASKETS_RF_ROC2.png'])
    st.image(['AGE_RF_ROC2.png', 'SMOTE_AGE_RF_ROC2.png'])

    st.write("The AUC for all baskets are shown as below:")
    a_file = open("BASKETS_RF_AUC2.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    st.write("The AUC for all AGE are shown as below:")
    a_file = open("AGE_RF_AUC2.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    
    st.write("The AUC for all baskets with smote are shown as below:")
    a_file = open("SMOTE_BASKETS_RF_AUC2.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")
    st.write("The AUC for all AGE with smote are shown as below:")
    a_file = open("SMOTE_AGE_RF_AUC2.txt")
    lines = a_file.readlines()
    for line in lines:
        st.write(line)
    st.write("\n")